const testGeneratingParams = [
    {
        title: "Fog", 
        defaultValue:"",
        getAriaValueText:"",
        step:"",
        min:"",
        max:"",
        marks:"",
        disabeld:"",
    }, 
    {
        title: "Wind", 
        defaultValue:"",
        getAriaValueText:"",
        step:"",
        min:"",
        max:"",
        marks:"",
        disabeld:"",
    },
    {
        title: "Density", 
        defaultValue:"",
        getAriaValueText:"",
        step:"",
        min:"",
        max:"",
        marks:"",
        disabeld:"",
    },
    {
        title: "Brightness", 
        defaultValue:"",
        getAriaValueText:"",
        step:"",
        min:"",
        max:"",
        marks:"",
        disabeld:"",
    },
    {
        title: "Cloudiness", 
        defaultValue:"",
        getAriaValueText:"",
        step:"",
        min:"",
        max:"",
        marks:"",
        disabeld:"",
    },
    {
        title: "Height", 
        defaultValue:"",
        getAriaValueText:"",
        step:"",
        min:"",
        max:"",
        marks:"",
        disabeld:"",
    },
]